http://localhost:3000/piadas


###

POST  http://localhost:3000/user/create
content-type: application/json

{
    "email": "rptl@gmail.com", 
    "password": "admin123"
}

###

POST  http://localhost:3000/user/auth
content-type: application/json

{
    "email": "rafa@gmail.com", 
    "password": "admin123"
}

###


http://localhost:3000/user/fetch
